### ISSUE TITLE
Old  on "first mapping [initial stage]" for more than 20 hours no progress, no log...

### ISSUE THREAD

**Issue by rLannes** [Chimera-tools/ChimPipe#18]
Hi,

I wanted to Try ChimPipe on RNA seq data on Drosophilia Melanogaster D.Mel.6
But the pipeline is stuck at the initial stage without any progress or log.. I may have forgot something but I can't tell what. any help would be greatly appreciated!

```
> tail  MappingPhase/FirstMapping/control1ChimPipe_firstMap.log 

------------ [ID:  5 -- 'stats'] [Depends On: merge_and_pair] ------------
               stats_json : True
                   paired : True
        Temporary Outputs : False
                  Outputs : /tmp/control1ChimPipe_firstMap.stats.txt
                          : /tmp/control1ChimPipe_firstMap.stats.json
--------------------------------------------------------------

Running step: initial
```

sdout:
```
Executing ChimPipe v0.9.6 for control1ChimPipe
----------------------------------------------

[PRELIM] Determining the offset quality of the reads for control1ChimPipe...
 quality=`Romain/Software/ChimPipe/src/bash/detect.fq.qual.sh Fastq_copy/merged/L459_1500_S1_merge_L001_R1_001.fastq.gz | awk '{print $2}'`
 The read quality is 33
done
Fri 02 Dec 2022 02:14:31 PM EST ***** Executing first mapping step *****
[FIRST-MAP] Running GEMtools rna pipeline on control1ChimPipe...
Software/ChimPipe/bin/gemtools-1.7.1-i3/gemtools --loglevel warn rna-pipeline -f Fastq_copy/merged/L459_1500_S1_merge_L001_R1_001.fastq.gz Fastq_copy/merged/L459_1500_S1_merge_L001_R2_001.fastq.gz -i /tmp/dmel-all-chromosome-r6.48.gem -a /tmp/dm6_sorted_gtf.gtf -r /tmp/dm6_sorted_gtf.gtf.junctions.gem -k /tmp/dm6_sorted_gtf.gtf.junctions.keys -q 33 --max-read-length 250 --max-intron-length 27549260 --min-split-size 15 --refinement-step 2 --junction-consensus GT+AG,GC+AG,ATATC+A.,GTATC+AT --no-filtered --no-bam --no-xs --no-count -n control1ChimPipe_firstMap --compress-all --output-dir /tmp -t 20 >> Jackie/Yloop_barck_dm6/transplicing/MappingPhase/FirstMapping/control1ChimPipe_firstMap.log 2>&1
```

any help would be appreciated.

I launched ChimPipe on a slurm cluster using this script:
```

#!/bin/bash 

#SBATCH --job-name=ChimPipe
#SBATCH --nodes=1                       # ensure cores are on one node
#SBATCH --ntasks=1                      # run a single task
#SBATCH --cpus-per-task=20               # number of cores/threads requested.  This is enforced.
#SBATCH --mem=32gb                      # memory requested.  This can be increased.
#SBATCH --partition=20  # partition (queue) to use
#SBATCH --output=ChimPipe.o%j         # File to which STDOUT will be written, %j inserts jobid


FASTQ_BASE=$1
out=$2
echo ${FASTQ_BASE}_R1_001.fastq.gz
echo ${FASTQ_BASE}_R2_001.fastq.gz


Romain/Software/ChimPipe/ChimPipe.sh  --fastq_1 ${FASTQ_BASE}_R1_001.fastq.gz  --fastq_2 ${FASTQ_BASE}_R2_001.fastq.gz  -g dmel-all-chromosome-r6.48.gem   -a dm6_sorted_gtf.gtf  -t dm6_sorted_gtf.gtf.junctions.gem -k dm6_sorted_gtf.gtf.junctions.keys --sample-id ${out}  --threads  20  --max-read-length 250
```

t-index cmd:
`/lab/solexa_yamashita/people/Romain/Software/ChimPipe/bin/gemtools-1.7.1-i3/gemtools t-index -i  dmel-all-chromosome-r6.48.gem -a  dm6_sorted_gtf.gtf`

index cmd
`/lab/solexa_yamashita/people/Romain/Software/ChimPipe/bin/gemtools-1.7.1-i3/gemtools index -i  dmel-all-chromosome-r6.48.fasta `

**Comment by rLannes** [comment]
Hi thank you for the answer,

I don't find mcf7 genome neither and example dir in the repo, where can i find it?

I can definitely share the gtf and the genome, those are the public latest Drosophilia dm6 on flybase.

How can I share them with you?

**Comment by sdjebali** [comment]
Hi,


In fact I was talking about this tutorial


https://chimpipe.readthedocs.io/en/latest/tutorial.html


if you manage to run chimpipe on these data it means the problem comes from the formatting of the drosophila data


do you mind trying the tutorial ?


In the mean time I can also inspect your gtf file, fasta file and the head of your fastq files ?


If you could just point me to the links from which you downloaded annotation gtf file and genome fasta file ? and copy paste here the head of read1 and read2 fastq files ?


thanks


----
Sarah Djebali - PhD - CR INSERM
Iron metabolism: from regulation to therapy
IRSD INSERM U1220 - Bat B - CHU Purpan
Place du Docteur Baylac - CS 60039
31024 Toulouse Cedex 3
sarah dot djebali at inserm dot fr


________________________________
De : rLannes ***@***.***>
Envoyé : dimanche 4 décembre 2022 16:55:26
À : Chimera-tools/ChimPipe
Cc : Sarah Djebali; Comment
Objet : Re: [Chimera-tools/ChimPipe] Old on "first mapping [initial stage]" for more than 20 hours no progress, no log... (Issue #18)


Hi thank you for the answer,

I don't find mcf7 genome neither and example dir in the repo, where can i find it?

I can definitely share the gtf and the genome, those are the public latest Drosophilia dm6 on flybase.

How can I share them with you?

**Comment by rLannes** [comment]
Well I can sure try the tutorial which is certainly a good point to start.
but when I try to download it I get a 403 forbbiden error "/rguigo/Papers/ChimPipe/ChimPipe_tutorial.tar.gz"

fastq header:
I had 2 technical replicate for each fastq. Before running ChimPipe, I merged them using "cat * fastq.gz> fastq.gz". I am  not sure that relevant.

```
> zcat Fastq_copy/merged/L45_S1_merge_L001_R1_001.fastq.gz | head
@A01100:127:HGLMCDRXY:1:2101:1759:1000 1:N:0:GACAGTAA+NTAATCGC
NTTTTTTCATAATTTTATTCATATAAATAAATTTATTGTAACCCATTATTACTTAAATATAAGCTACACCTTGATCTGATATAAATTTTTATTAAAATTATTGAATATTATTATTCTTATAAAATATTCTGATAACGACGGTATATAAACTGATTACAAATTTAAGTAAGGTCCATCGTGGATTATCGATTAAAAAACAGGTTCCTCTAGATAGACTAAAATACCGCCAAATTTTTTAAGTTTCAAGAACA
+
#FFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF,FFFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF:F:FFFFFF:F,FFFFFFFFFFFF:FFFF
@A01100:127:HGLMCDRXY:1:2101:3911:1000 1:N:0:GACAGTAA+NTAATCGC
NTCCCTAGCTATTGATGCCGTTGATTCTCGATTTAAAATTTAAGTTACACACAACCGGATTACAACAGACGGAAAGGACATGCACAAGAGGTTTTAGTTTGTTTGGTTTTAGTTTCTCAAATGTTAAAAATGGTAGTGAAAGCGGGTCTACAACGACAAAGGCACTGTTTGGTGTGGATCTGAGACTCGCTCCAAGGCATTAGGTGTTCTTTTTCATTGTCATCTCGTGGGCGGTGCGCAGACGTCGTCTG
+
#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF,FFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F,FFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F:FFFF
@A01100:127:HGLMCDRXY:1:2101:4164:1000 1:N:0:GACAGTAA+NTAATCGC
NGCGGCGGCACGAAGAACACCCACACAAACAGCAGCTCCGGCCATGGCGCCGCGGTACTGGTCCATACCCGTCTTGGGCTTCAGGCACAAGCCACCACTGTGGAAGGTCAGACCCTGGCCGAGCAGCAGAACGGGACGATCCTCGGGCGTGGTGCCGCAGTAGCTGCACTCCAGCAATAGAGGTGGTTCGCACGAACCCTTGGCGATCATTAGGAAGGAATTGAGGTTCATATCCTCGATCCAGTCCATGG
> zcat Fastq_copy/merged/L45_1500_S1_merge_L001_R2_001.fastq.gz | head
@A01100:127:HGLMCDRXY:1:2101:1759:1000 2:N:0:GACAGTAA+NTAATCGC
ATTAAATTAAATTTATTAATAATAATAATAAAATTAAATATATTAAGTGAAATTTTATATTTAAATTATTATATAAAAATGTAATTGAGGTTAAAAAATTTTAATAAAAAACTAGGATTAGATACCCTATTATTTAAAATGTAAATAAATTGCTAAAGTAGTAATAGTTATGTTCTTGAAACTTAAAAAATTTGGCGGTATTTTAGTCTATCTAGAGGAACCTGTTTTTTAATCGATAATCCACGATGGAC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFF:,::FFFF,FFFFFFFFFFF,FFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF,FFF:,FFFF:F,F,FFF::FFFFFFFFF:FFFFFFFFF:FFFFFFFFF:F,FFFFFFF:F:FFFF,:F,FFFFFFFFFFF,FFFFF,FFFF:FFFFFFFFF
@A01100:127:HGLMCDRXY:1:2101:3911:1000 2:N:0:GACAGTAA+NTAATCGC
GAACATTTCGTGTGCGCCAAGTGCGAGAAACCCTTCTTGGGTCACCGACACTACGAGAAGCGGGGATTGGCCTACTGCGAGACGCACTATCATCAGCTCTTTGGCAACCTGTGCTTCGTCTGCAACCAAGTTATTGGAGGCGATGTTTTCACTGCCTTGAACAAGGCCTGGTGTGTGCACCACTTTGCGTGCTCCGTGTGCGACACGAAGATGACACAAAAATCGAAATTCTACGAGTACGACGAGAAGCC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFF:FFFFFFFF,FFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF
@A01100:127:HGLMCDRXY:1:2101:4164:1000 2:N:0:GACAGTAA+NTAATCGC
CCGGGATGCCTGGGTGCGTGGTCTGTTCAAGGCAGAATCCCAGAATTTGGCCAGACGTTTGTCCGACACGCCTGCCAATATGATGACGCCCTCGATATTCGCACAGGCCGCCGTGGATGCCTTGTGCCCGTGCGGTGTTTCCGTGGAGGTGCGCTCCATGGACTGGATCGAGGATATGAACCTCAATTCCTTCCTAATGATCGCCAAGGGTTCGTGCGAACCACCTCTATTGCTGGAGTGCAGCTACTGCG

```


fasta:
http://ftp.flybase.net/releases/FB2022_05/dmel_r6.48/fasta/dmel-all-chromosome-r6.48.fasta.gz
gtf:
http://ftp.flybase.net/releases/FB2022_05/dmel_r6.48/gtf/dmel-all-r6.48.gtf.gz

**Comment by sdjebali** [comment]
Sorry I did not  remember this issue


I have put the data here

https://genoweb.toulouse.inra.fr/~sdjebali/chimpipe/mcf7.tutorial/


But I also would like to know if you encountered any problem when making  the genome and the transcriptome gem files ? were any of these two gem files empty ?


Indeed I can already see something to change in the genome file, since ChimPipe is not able to use genome fasta files with headers that contain more than the chromosome name.


There is a command to strip all the rest, just do this

sed 's/ .*//' genome.fa > genome_processed.fa

and repeat the genome and transcriptome gem file calling with this new genome file ?


It would also be safer to edit your gtf file so that it only has exon rows and has gene_id and transcript_id as the two first (key,value) pairs in the 9th field


You can do it like this (awk script is in the mcf7.tutorial directory above)

awk '$3=="exon"' annot.gtf | awk -f  make_gff_ok.awk> annot.exons.ok.gff


and use this exon file when making the transcriptome gem file ?


Best,


----
Sarah Djebali - PhD - CR INSERM
Iron metabolism: from regulation to therapy
IRSD INSERM U1220 - Bat B - CHU Purpan
Place du Docteur Baylac - CS 60039
31024 Toulouse Cedex 3
sarah dot djebali at inserm dot fr


________________________________
De : rLannes ***@***.***>
Envoyé : lundi 5 décembre 2022 15:12:01
À : Chimera-tools/ChimPipe
Cc : Sarah Djebali; Comment
Objet : Re: [Chimera-tools/ChimPipe] Old on "first mapping [initial stage]" for more than 20 hours no progress, no log... (Issue #18)


Well I can sure try the tutorial which is certainly a good point to start.
but when I try to download it I get a 403 forbbiden error "/rguigo/Papers/ChimPipe/ChimPipe_tutorial.tar.gz"

fastq header:
I had 2 technical replicate for each fastq. Before running ChimPipe, I merged them using "cat * fastq.gz> fastq.gz". I am not sure that relevant.

> zcat Fastq_copy/merged/L45_S1_merge_L001_R1_001.fastq.gz | head
@A01100:127:HGLMCDRXY:1:2101:1759:1000 1:N:0:GACAGTAA+NTAATCGC
NTTTTTTCATAATTTTATTCATATAAATAAATTTATTGTAACCCATTATTACTTAAATATAAGCTACACCTTGATCTGATATAAATTTTTATTAAAATTATTGAATATTATTATTCTTATAAAATATTCTGATAACGACGGTATATAAACTGATTACAAATTTAAGTAAGGTCCATCGTGGATTATCGATTAAAAAACAGGTTCCTCTAGATAGACTAAAATACCGCCAAATTTTTTAAGTTTCAAGAACA
+
#FFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF,FFFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF:F:FFFFFF:F,FFFFFFFFFFFF:FFFF
@A01100:127:HGLMCDRXY:1:2101:3911:1000 1:N:0:GACAGTAA+NTAATCGC
NTCCCTAGCTATTGATGCCGTTGATTCTCGATTTAAAATTTAAGTTACACACAACCGGATTACAACAGACGGAAAGGACATGCACAAGAGGTTTTAGTTTGTTTGGTTTTAGTTTCTCAAATGTTAAAAATGGTAGTGAAAGCGGGTCTACAACGACAAAGGCACTGTTTGGTGTGGATCTGAGACTCGCTCCAAGGCATTAGGTGTTCTTTTTCATTGTCATCTCGTGGGCGGTGCGCAGACGTCGTCTG
+
#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF,FFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F,FFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F:FFFF
@A01100:127:HGLMCDRXY:1:2101:4164:1000 1:N:0:GACAGTAA+NTAATCGC
NGCGGCGGCACGAAGAACACCCACACAAACAGCAGCTCCGGCCATGGCGCCGCGGTACTGGTCCATACCCGTCTTGGGCTTCAGGCACAAGCCACCACTGTGGAAGGTCAGACCCTGGCCGAGCAGCAGAACGGGACGATCCTCGGGCGTGGTGCCGCAGTAGCTGCACTCCAGCAATAGAGGTGGTTCGCACGAACCCTTGGCGATCATTAGGAAGGAATTGAGGTTCATATCCTCGATCCAGTCCATGG
> zcat Fastq_copy/merged/L45_1500_S1_merge_L001_R2_001.fastq.gz | head
@A01100:127:HGLMCDRXY:1:2101:1759:1000 2:N:0:GACAGTAA+NTAATCGC
ATTAAATTAAATTTATTAATAATAATAATAAAATTAAATATATTAAGTGAAATTTTATATTTAAATTATTATATAAAAATGTAATTGAGGTTAAAAAATTTTAATAAAAAACTAGGATTAGATACCCTATTATTTAAAATGTAAATAAATTGCTAAAGTAGTAATAGTTATGTTCTTGAAACTTAAAAAATTTGGCGGTATTTTAGTCTATCTAGAGGAACCTGTTTTTTAATCGATAATCCACGATGGAC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFF:,::FFFF,FFFFFFFFFFF,FFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF,FFF:,FFFF:F,F,FFF::FFFFFFFFF:FFFFFFFFF:FFFFFFFFF:F,FFFFFFF:F:FFFF,:F,FFFFFFFFFFF,FFFFF,FFFF:FFFFFFFFF
@A01100:127:HGLMCDRXY:1:2101:3911:1000 2:N:0:GACAGTAA+NTAATCGC
GAACATTTCGTGTGCGCCAAGTGCGAGAAACCCTTCTTGGGTCACCGACACTACGAGAAGCGGGGATTGGCCTACTGCGAGACGCACTATCATCAGCTCTTTGGCAACCTGTGCTTCGTCTGCAACCAAGTTATTGGAGGCGATGTTTTCACTGCCTTGAACAAGGCCTGGTGTGTGCACCACTTTGCGTGCTCCGTGTGCGACACGAAGATGACACAAAAATCGAAATTCTACGAGTACGACGAGAAGCC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFF:FFFFFFFF,FFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF
@A01100:127:HGLMCDRXY:1:2101:4164:1000 2:N:0:GACAGTAA+NTAATCGC
CCGGGATGCCTGGGTGCGTGGTCTGTTCAAGGCAGAATCCCAGAATTTGGCCAGACGTTTGTCCGACACGCCTGCCAATATGATGACGCCCTCGATATTCGCACAGGCCGCCGTGGATGCCTTGTGCCCGTGCGGTGTTTCCGTGGAGGTGCGCTCCATGGACTGGATCGAGGATATGAACCTCAATTCCTTCCTAATGATCGCCAAGGGTTCGTGCGAACCACCTCTATTGCTGGAGTGCAGCTACTGCG



fasta:
http://ftp.flybase.net/releases/FB2022_05/dmel_r6.48/fasta/dmel-all-chromosome-r6.48.fasta.gz
gtf:
http://ftp.flybase.net/releases/FB2022_05/dmel_r6.48/gtf/dmel-all-r6.48.gtf.gz

**Comment by rLannes** [comment]
trying it overnight. I keep you updated! thank you so much

**Comment by rLannes** [comment]
I rerun using a custom tmp dir inside there where log file.
one with the error descibed there: https://github.com/Chimera-tools/ChimPipe/issues/2

I am not root on the server, I am contacting the sys admin to see if he can fix it.
I am closing this thread, as the issue seems to be with gemtools now.

Thank you for your help.
Best,
